import React from "react";
import { FaUser } from "react-icons/fa";
import { FaBuildingColumns } from "react-icons/fa6";
import { MdVerifiedUser } from "react-icons/md";
import { IoDocumentText } from "react-icons/io5";

export const INITIAL_VALUES = {
  customerCnic: "",
  customerEmail: "",
  customerMobile: "",
  customerOperator: "",
  isWelcome: false,
  isResumeApplication: false,
  isVerification: false,
  isMobileOtpVerification: false,
  isEmailOtpVerification: false,
};

export const PATHS = {
  ageConfirmation: "age-confirmation",
};

export const OPERATOR_OPTION = [
  { value: "1", label: "Zong" },
  { value: "2", label: "Jazz" },
  { value: "3", label: "Telenor" },
  { value: "4", label: "Uphone" },
];

export const LINKS_TO_DASHBOARD_FORMS = [
  {
    icon: React.createElement(FaUser, {
      style: { color: "#5093e0", marginRight: "15px", fontSize: "18px" },
    }),
    text: "Personal Information",
    link: `/dashboard/personal-information`,
  },
  {
    icon: React.createElement(FaBuildingColumns, {
      style: { color: "#5093e0", marginRight: "15px", fontSize: "18px" },
    }),
    text: "Contact Information",
    link: `/dashboard/contact-information`,
  },
  {
    icon: React.createElement(MdVerifiedUser, {
      style: { color: "#5093e0", marginRight: "15px", fontSize: "20px" },
    }),
    text: "Cnic Verification",
    link: `/dashboard/cnic-verification`,
  },
  {
    icon: React.createElement(IoDocumentText, {
      style: { color: "#5093e0", marginRight: "15px", fontSize: "20px" },
    }),
    text: "Document Upload",
    link: `/dashboard/upload-document`,
  },
];

export const LIST_OF_PROVINCES = [
  { label: "Punjab", value: "101" },
  { label: "Sindh", value: "102" },
  { label: "Khyber Pakhtunkhwa", value: "103" },
  { label: "Balochistan", value: "104" },
  { label: "Gilgit-Baltistan", value: "105" },
  { label: "Azad Jammu and Kashmir", value: "106" },
  { label: "Islamabad Capital Territory", value: "107" },
];

export const LIST_OF_CITIES = [
  { label: "Karachi", value: "136" },
  { label: "Lahore", value: "165" },
  { label: "Islamabad", value: "106" },
  { label: "Rawalpindi", value: "259" },
  { label: "Peshawar", value: "233" },
  { label: "Faisalabad", value: "70" },
  { label: "Multan", value: "201" },
  { label: "Abbotabad", value: "1" },
  { label: "Abdul Hakeem", value: "2" },
  { label: "Ahmedpur East", value: "3" },
  { label: "Akora Khatak", value: "4" },
  { label: "Alipur Chatta", value: "5" },
  { label: "Arifwala", value: "6" },
  { label: "Attock", value: "7" },
  { label: "Awaran", value: "8" },
  { label: "Badin", value: "9" },
  { label: "Bagh", value: "10" },
  { label: "Baharan", value: "11" },
  { label: "Bahawalnagar", value: "12" },
  { label: "Bahawalpur", value: "13" },
  { label: "Baipheru", value: "14" },
  { label: "Bajur", value: "15" },
  { label: "Balakot", value: "16" },
  { label: "Baltistan", value: "17" },
  { label: "Bangwal", value: "18" },
  { label: "Bannu", value: "19" },
  { label: "Barape", value: "20" },
  { label: "Barkhan", value: "21" },
  { label: "Batgram", value: "22" },
  { label: "Batkhela", value: "23" },
  { label: "Bela", value: "24" },
  { label: "Bhakkar", value: "25" },
  { label: "Bhera", value: "26" },
  { label: "Bhimber", value: "27" },
  { label: "Bhirya Road", value: "28" },
  { label: "Bhitshah", value: "29" },
  { label: "Bhurewala", value: "30" },
  { label: "Bisham", value: "31" },
  { label: "Bolan", value: "32" },
  { label: "Bunner", value: "33" },
  { label: "Cantt Shorkot", value: "34" },
  { label: "Chaghi", value: "35" },
  { label: "Chaklala", value: "36" },
  { label: "Chakwal", value: "37" },
  { label: "Chaman", value: "38" },
  { label: "Charsadda", value: "39" },
  { label: "Chichawatni", value: "40" },
  { label: "Chichikomalia", value: "41" },
  { label: "Chikar", value: "42" },
  { label: "Chinot", value: "43" },
  { label: "Chishtian", value: "44" },
  { label: "Chitral", value: "45" },
  { label: "Chouk Azam", value: "46" },
  { label: "Chowkmunda", value: "47" },
  { label: "Chunain", value: "48" },
  { label: "D G Khan", value: "49" },
  { label: "D I Khan", value: "50" },
  { label: "Dadu", value: "51" },
  { label: "Dagar", value: "52" },
  { label: "Dalbadin", value: "53" },
  { label: "Dara Adamkhel", value: "54" },
  { label: "Dariakhan", value: "55" },
  { label: "Daska", value: "56" },
  { label: "Deena", value: "57" },
  { label: "Deepalpur", value: "58" },
  { label: "Dera Bughti", value: "59" },
  { label: "Dera Murad Jamali", value: "60" },
  { label: "Dharki", value: "61" },
  { label: "Dhudyal", value: "62" },
  { label: "Diamir", value: "63" },
  { label: "Dir", value: "64" },
  { label: "Dirkot ", value: "66" },
  { label: "Dunyapur", value: "67" },
  { label: "Eimanabad", value: "68" },
  { label: "Essakhel", value: "69" },
  { label: "Farooqaabad", value: "71" },
  { label: "Fateh Jang", value: "72" },
  { label: "Fatehpur", value: "73" },
  { label: "Fort Abbas", value: "74" },
  { label: "Gadooon amzai", value: "75" },
  { label: "Gambat", value: "76" },
  { label: "Garmaraja", value: "77" },
  { label: "Gawadar", value: "78" },
  { label: "Ghanchee", value: "79" },
  { label: "Ghizer", value: "80" },
  { label: "Ghotki", value: "81" },
  { label: "Gijkopt", value: "82" },
  { label: "Gilgit", value: "83" },
  { label: "Gjhakar", value: "84" },
  { label: "Gojra", value: "85" },
  { label: "Gomal", value: "86" },
  { label: "Gujarkhan", value: "87" },
  { label: "Gujranwala", value: "88" },
  { label: "Gujrat", value: "89" },
  { label: "Hafizabad", value: "90" },
  { label: "Hala", value: "91" },
  { label: "Hangu ", value: "92" },
  { label: "Haripur", value: "93" },
  { label: "Haroonabad", value: "94" },
  { label: "Harpa", value: "95" },
  { label: "Hasilpur", value: "96" },
  { label: "Hassan Abdal", value: "97" },
  { label: "Hatian", value: "98" },
  { label: "Hattar", value: "99" },
  { label: "Havail Lakka", value: "100" },
  { label: "Havelly", value: "101" },
  { label: "Hazaru", value: "102" },
  { label: "Hub", value: "103" },
  { label: "Humak", value: "104" },
  { label: "Hyderabad", value: "105" },
  { label: "Jacobabad", value: "107" },
  { label: "Jaffarabad", value: "108" },
  { label: "Jahanian", value: "109" },
  { label: "Jalalpur Jatta", value: "110" },
  { label: "Jamrood", value: "111" },
  { label: "Jaranwala", value: "112" },
  { label: "Jehangira", value: "113" },
  { label: "Jhal Magsi", value: "114" },
  { label: "Jhang", value: "115" },
  { label: "Jhelum", value: "116" },
  { label: "Jhudo", value: "117" },
  { label: "Joharabad", value: "118" },
  { label: "Kabirwala", value: "119" },
  { label: "Kahan Gharh", value: "120" },
  { label: "Kahirpur Tamewali", value: "121" },
  { label: "Kahka Dogra", value: "122" },
  { label: "Kahuta", value: "123" },
  { label: "Kakul", value: "124" },
  { label: "Kalabath", value: "125" },
  { label: "Kalorkot", value: "126" },
  { label: "Kamalia", value: "127" },
  { label: "Kamber Ali Khan", value: "128" },
  { label: "Kamoki", value: "129" },
  { label: "Kamra", value: "130" },
  { label: "Kana Kacha", value: "131" },
  { label: "Kandhkot", value: "132" },
  { label: "Kandiaro", value: "133" },
  { label: "Kanpur", value: "134" },
  { label: "Karak", value: "140" },
  { label: "Karoor Pakka", value: "141" },
  { label: "Kashmore", value: "142" },
  { label: "Kasur", value: "143" },
  { label: "Kech", value: "144" },
  { label: "Khairpur Miris", value: "145" },
  { label: "Khanewal", value: "146" },
  { label: "Kharan", value: "147" },
  { label: "Kheairan", value: "148" },
  { label: "Khipro", value: "149" },
  { label: "Khushab", value: "150" },
  { label: "Khuzdar", value: "151" },
  { label: "Khyber Agency", value: "152" },
  { label: "Kila Saifullah", value: "153" },
  { label: "Killa Abdullah", value: "154" },
  { label: "Kohat", value: "155" },
  { label: "Kohistan", value: "156" },
  { label: "Kohlu", value: "157" },
  { label: "Kot Momen", value: "158" },
  { label: "Kot Najibullah", value: "159" },
  { label: "Kot Radha Kishan", value: "160" },
  { label: "Kotadu", value: "161" },
  { label: "Kotli", value: "162" },
  { label: "Kunri", value: "163" },
  { label: "Kurram Agency", value: "164" },
  { label: "Laki Marwat", value: "166" },
  { label: "Lalabagh", value: "167" },
  { label: "Lalamusa", value: "168" },
  { label: "Landi Kotal", value: "169" },
  { label: "Laranspur", value: "170" },
  { label: "Larkana", value: "171" },
  { label: "Lasbela", value: "172" },
  { label: "Latamber", value: "173" },
  { label: "Layyah", value: "174" },
  { label: "Liquatabad", value: "175" },
  { label: "Lodhran", value: "176" },
  { label: "Loralai", value: "177" },
  { label: "Mailsi", value: "178" },
  { label: "Malakand", value: "179" },
  { label: "Mamun Kanjan", value: "180" },
  { label: "Mandi Bahauddin", value: "181" },
  { label: "Mangla", value: "182" },
  { label: "Mansehra", value: "183" },
  { label: "Mardan", value: "184" },
  { label: "Mastung", value: "185" },
  { label: "Matli", value: "186" },
  { label: "Matri", value: "187" },
  { label: "Mehrabpur", value: "188" },
  { label: "Mianwali", value: "189" },
  { label: "Minan Chanu", value: "190" },
  { label: "Mingora", value: "191" },
  { label: "Mir Pur Khas", value: "192" },
  { label: "Mirali Bnu", value: "193" },
  { label: "Miranshah", value: "194" },
  { label: "Mirpur AK", value: "195" },
  { label: "Mirpur Mathelo", value: "196" },
  { label: "Mithan Kot", value: "197" },
  { label: "Mohmand Agency", value: "198" },
  { label: "Mor Kunda", value: "199" },
  { label: "Moro", value: "200" },
  { label: "Murri", value: "202" },
  { label: "Musakhel", value: "203" },
  { label: "Mustafaabad", value: "204" },
  { label: "Muzaffarabad", value: "205" },
  { label: "Muzaffargarh", value: "206" },
  { label: "Nakyal", value: "207" },
  { label: "Nankana Sahb", value: "208" },
  { label: "Narowal", value: "209" },
  { label: "Nasirabad", value: "210" },
  { label: "Nathia Gali", value: "211" },
  { label: "Nawabshah", value: "212" },
  { label: "Nawankali", value: "213" },
  { label: "New Jatoi", value: "214" },
  { label: "Newsero", value: "215" },
  { label: "Nooroabad", value: "216" },
  { label: "Norangmandi", value: "217" },
  { label: "North Waziristan Agency", value: "218" },
  { label: "Noshkli", value: "219" },
  { label: "Nowshera", value: "220" },
  { label: "Nowshero Feroz", value: "221" },
  { label: "Okara", value: "222" },
  { label: "Orakazi Agency", value: "223" },
  { label: "Padidan", value: "224" },
  { label: "Pak Patan", value: "225" },
  { label: "Panjgur", value: "226" },
  { label: "Pano Aqil", value: "227" },
  { label: "Parachanar", value: "228" },
  { label: "Pashin", value: "229" },
  { label: "Pasni", value: "230" },
  { label: "Pasroor", value: "231" },
  { label: "Patoki", value: "232" },
  { label: "Phalia", value: "234" },
  { label: "Pinddadan Khan", value: "235" },
  { label: "Pindibhatian", value: "236" },
  { label: "Pindigheb", value: "237" },
  { label: "Pir Jo Goth", value: "238" },
  { label: "Pir Mahal", value: "239" },
  { label: "Pisjhin", value: "240" },
  { label: "Plundri", value: "241" },
  { label: "Poonch", value: "242" },
  { label: "Pubi", value: "243" },
  { label: "Qaidabad", value: "244" },
  { label: "Qalat", value: "245" },
  { label: "Qazi Ahmed", value: "246" },
  { label: "Qila Deedar Singh", value: "247" },
  { label: "Qilla Shekhupura", value: "248" },
  { label: "Quetta", value: "249" },
  { label: "Rabwah", value: "250" },
  { label: "Rahim Yar Khan", value: "252" },
  { label: "Rahwali", value: "253" },
  { label: "Raiwind", value: "254" },
  { label: "Rajanpur", value: "255" },
  { label: "Rani Pur", value: "256" },
  { label: "Ratodero", value: "257" },
  { label: "Rawalakot", value: "258" },
  { label: "Rawat", value: "260" },
  { label: "Renla Kurd", value: "261" },
  { label: "Risalpur", value: "262" },
  { label: "Sadiqabad", value: "263" },
  { label: "Sahiwal", value: "264" },
  { label: "Sajawal", value: "265" },
  { label: "Sakha Kot", value: "266" },
  { label: "Sambrial", value: "267" },
  { label: "Sanghar ", value: "268" },
  { label: "Sarai Morang", value: "269" },
  { label: "Sargodha", value: "270" },
  { label: "Sawabi", value: "271" },
  { label: "Sewan Sharif", value: "272" },
  { label: "Shah Kot", value: "273" },
  { label: "Shah Pur ", value: "274" },
  { label: "Shahdadkot", value: "275" },
  { label: "Shahdadpur", value: "276" },
  { label: "Shakargarah", value: "277" },
  { label: "Shangla Hill", value: "278" },
  { label: "Sharkpur", value: "279" },
  { label: "Sheikhupura", value: "280" },
  { label: "Shijaabad", value: "281" },
  { label: "Shikarpur", value: "282" },
  { label: "Shorkot", value: "283" },
  { label: "Sialkot", value: "284" },
  { label: "Sibi", value: "285" },
  { label: "Sidu Sharif", value: "286" },
  { label: "Sihala", value: "287" },
  { label: "Skardu", value: "288" },
  { label: "Skrand", value: "289" },
  { label: "Smandri", value: "290" },
  { label: "South Waziristan Agy", value: "291" },
  { label: "Sudhnoti", value: "292" },
  { label: "Sukkur", value: "293" },
  { label: "Swat", value: "294" },
  { label: "Taftan", value: "295" },
  { label: "Takht Bhai", value: "296" },
  { label: "Takht Nusrati", value: "297" },
  { label: "Talagang", value: "298" },
  { label: "Tall", value: "299" },
  { label: "Tandinawala", value: "300" },
  { label: "Tando Adma Khan", value: "301" },
  { label: "Tando Allahyar", value: "302" },
  { label: "Tando Bago", value: "303" },
  { label: "Tando Jam", value: "304" },
  { label: "Tando M. Khan", value: "305" },
  { label: "Tank", value: "306" },
  { label: "Taru Shah", value: "307" },
  { label: "Taxillan", value: "308" },
  { label: "Tharparkar", value: "309" },
  { label: "Thatta", value: "310" },
  { label: "Thull", value: "311" },
  { label: "Timargarah", value: "312" },
  { label: "Toba Tek Singh", value: "313" },
  { label: "Tunsa", value: "314" },
  { label: "Turbat", value: "315" },
  { label: "Uch Sharif", value: "316" },
  { label: "Umer Kot", value: "317" },
  { label: "Usta Muhammad", value: "318" },
  { label: "Uttal", value: "319" },
  { label: "Vehari", value: "320" },
  { label: "Wah Cantt", value: "321" },
  { label: "War", value: "322" },
  { label: "Wazirabad", value: "323" },
  { label: "Wirkan", value: "324" },
  { label: "Yasman", value: "325" },
  { label: "Zafarwal", value: "326" },
  { label: "Zhob", value: "327" },
  { label: "Ziarat", value: "328" },
  { label: "Kotri", value: "329" },
  { label: "Jamshoro", value: "330" },
  { label: "Washuk", value: "331" },
  { label: "Jalal Pur Pirwala", value: "332" },
  { label: "Neelam", value: "333" },
  { label: "Judba", value: "334" },
];
